DB_FILE = None
GENRES = []
RATING = 90
RATING_IN_GENRE = 0
EXCLUSIONS = []
POPULARITY = 0
ANIME_PROCESSING_NUMBER = 0
ANIME_LIST = []
ANIME_CONFIRM_LIST = []
SEASON_LIST = ['WINTER', 'SPRING', 'SUMMER', 'FALL']
SEASON = None
SEASON_YEAR = 0
SEASON_COLOR = None
SEASON_COLOR_DARK = None
SEASON_THEME_PRIMARY = ''
SEASON_NAME = 'Winter'
Test = 'hi'
EP_PAGE_EPISODE = None
EP_PAGE_ANIME = None
aclass= None

EPISODE_PAGE_CLASS = None
HOME_CLASS = None
MAIN_WIDGET = None

ROMAJI_LIST = []
ENG_LIST = []
CUSTOM_LIST = []
